#include "libpath0.inc"
#include "..\bin\pctcpudp.h"

#include "prg\run_prgv.h"
#include "prg\run_prgl.h"
#include "prg\run_prgr.h"
#include "prg\version.h"

#include "prg\blocking.c"
#include "prg\every_c.c"
#include "prg\every_s.c"
#include "prg\every_t.c"
#include "prg\input_a.c"
#include "prg\input_d.c"
#include "prg\other.c"
#include "prg\ouput_a.c"
#include "prg\ouput_d.c"
#include "prg\start.c"
#include "prg\update_s.c"
#include "prg\update_t.c"
