//----------------------------------------------------------------------------
//  Обновление значений каждую секунду
vd  far UpdDataS(vd){

    //-----------------------------------------------------------------------
    // Установка переменной, отображающей работоспособность сети
    NetLive__V++; if(NetLive__V>8){ NetLive__V=0; }
    //------------------------------------------------------------------------
    // флаг работы контроллера
    DONCSW___V = (DONCSW___V == OFF) then_ ON else_ OFF;
    //------------------------------------------------------------------------


    //------------------------------------------------------------------------
    // Передача значений сигнализации и диапазонов

    AITHDF_SZV=AITHDF_SZM;  AITHDF_SDV=AITHDF_SDM;  AITHDF__FV=AITHDF__FM;
    AITHDF__AV=AITHDF__AM;  AITHDF_AZV=AITHDF_AZM;  AITHDF_AMV=AITHDF_AMM;

    AITGDF_SZV=AITGDF_SZM;  AITGDF_SDV=AITGDF_SDM;  AITGDF__FV=AITGDF__FM;
    AITGDF__AV=AITGDF__AM;  AITGDF_AZV=AITGDF_AZM;  AITGDF_AMV=AITGDF_AMM;

    AIT1ST_SZV=AIT1ST_SZM;  AIT1ST_SDV=AIT1ST_SDM;  AIT1ST__FV=AIT1ST__FM;
    AIT1ST__AV=AIT1ST__AM;  AIT1ST_AZV=AIT1ST_AZM;  AIT1ST_AMV=AIT1ST_AMM;

    AITF1D_SZV=AITF1D_SZM;  AITF1D_SDV=AITF1D_SDM;  AITF1D__FV=AITF1D__FM;
    AITF1D__AV=AITF1D__AM;  AITF1D_AZV=AITF1D_AZM;  AITF1D_AMV=AITF1D_AMM;

    AIT2ST_SZV=AIT2ST_SZM;  AIT2ST_SDV=AIT2ST_SDM;  AIT2ST__FV=AIT2ST__FM;
    AIT2ST__AV=AIT2ST__AM;  AIT2ST_AZV=AIT2ST_AZM;  AIT2ST_AMV=AIT2ST_AMM;

    AIT1GR_SZV=AIT1GR_SZM;  AIT1GR_SDV=AIT1GR_SDM;  AIT1GR__FV=AIT1GR__FM;
    AIT1GR__AV=AIT1GR__AM;  AIT1GR_AZV=AIT1GR_AZM;  AIT1GR_AMV=AIT1GR_AMM;

    AIT2GR_SZV=AIT2GR_SZM;  AIT2GR_SDV=AIT2GR_SDM;  AIT2GR__FV=AIT2GR__FM;
    AIT2GR__AV=AIT2GR__AM;  AIT2GR_AZV=AIT2GR_AZM;  AIT2GR_AMV=AIT2GR_AMM;

    AITNS1_SZV=AITNS1_SZM;  AITNS1_SDV=AITNS1_SDM;  AITNS1__FV=AITNS1__FM;
    AITNS1__AV=AITNS1__AM;  AITNS1_AZV=AITNS1_AZM;  AITNS1_AMV=AITNS1_AMM;

    //--------------------

    AITNS2_SZV=AITNS2_SZM;  AITNS2_SDV=AITNS2_SDM;  AITNS2__FV=AITNS2__FM;
    AITNS2__AV=AITNS2__AM;  AITNS2_AZV=AITNS2_AZM;  AITNS2_AMV=AITNS2_AMM;

    AITPBM_SZV=AITPBM_SZM;  AITPBM_SDV=AITPBM_SDM;  AITPBM__FV=AITPBM__FM;
    AITPBM__AV=AITPBM__AM;  AITPBM_AZV=AITPBM_AZM;  AITPBM_AMV=AITPBM_AMM;

    AITF1P_SZV=AITF1P_SZM;  AITF1P_SDV=AITF1P_SDM;  AITF1P__FV=AITF1P__FM;
    AITF1P__AV=AITF1P__AM;  AITF1P_AZV=AITF1P_AZM;  AITF1P_AMV=AITF1P_AMM;

    AITDVP_SZV=AITDVP_SZM;  AITDVP_SDV=AITDVP_SDM;  AITDVP__FV=AITDVP__FM;
    AITDVP__AV=AITDVP__AM;  AITDVP_AZV=AITDVP_AZM;  AITDVP_AMV=AITDVP_AMM;

    AIX0204SZV=AIX0204SZM;  AIX0204SDV=AIX0204SDM;  AIX0204_FV=AIX0204_FM;
    AIX0204_AV=AIX0204_AM;  AIX0204AZV=AIX0204AZM;  AIX0204AMV=AIX0204AMM;

    AIX0205SZV=AIX0205SZM;  AIX0205SDV=AIX0205SDM;  AIX0205_FV=AIX0205_FM;
    AIX0205_AV=AIX0205_AM;  AIX0205AZV=AIX0205AZM;  AIX0205AMV=AIX0205AMM;

    AIX0206SZV=AIX0206SZM;  AIX0206SDV=AIX0206SDM;  AIX0206_FV=AIX0206_FM;
    AIX0206_AV=AIX0206_AM;  AIX0206AZV=AIX0206AZM;  AIX0206AMV=AIX0206AMM;

    AIX0207SZV=AIX0207SZM;  AIX0207SDV=AIX0207SDM;  AIX0207_FV=AIX0207_FM;
    AIX0207_AV=AIX0207_AM;  AIX0207AZV=AIX0207AZM;  AIX0207AMV=AIX0207AMM;

    //--------------------

    AIPGOK_SZV=AIPGOK_SZM;  AIPGOK_SDV=AIPGOK_SDM;  AIPGOK__FV=AIPGOK__FM;
    AIPGOK__AV=AIPGOK__AM;  AIPGOK_AZV=AIPGOK_AZM;  AIPGOK_AMV=AIPGOK_AMM;

    AIPZNS1SZV=AIPZNS1SZM;  AIPZNS1SDV=AIPZNS1SDM;  AIPZNS1_FV=AIPZNS1_FM;
    AIPZNS1_AV=AIPZNS1_AM;  AIPZNS1AZV=AIPZNS1AZM;  AIPZNS1AMV=AIPZNS1AMM;

    AIPZNS2SZV=AIPZNS2SZM;  AIPZNS2SDV=AIPZNS2SDM;  AIPZNS2_FV=AIPZNS2_FM;
    AIPZNS2_AV=AIPZNS2_AM;  AIPZNS2AZV=AIPZNS2AZM;  AIPZNS2AMV=AIPZNS2AMM;

    AIPNZKFSZV=AIPNZKFSZM;  AIPNZKFSDV=AIPNZKFSDM;  AIPNZKF_FV=AIPNZKF_FM;
    AIPNZKF_AV=AIPNZKF_AM;  AIPNZKFAZV=AIPNZKFAZM;  AIPNZKFAMV=AIPNZKFAMM;

    AIPVKIPSZV=AIPVKIPSZM;  AIPVKIPSDV=AIPVKIPSDM;  AIPVKIP_FV=AIPVKIP_FM;
    AIPVKIP_AV=AIPVKIP_AM;  AIPVKIPAZV=AIPVKIPAZM;  AIPVKIPAMV=AIPVKIPAMM;

    AIX0305SZV=AIX0305SZM;  AIX0305SDV=AIX0305SDM;  AIX0305_FV=AIX0305_FM;
    AIX0305_AV=AIX0305_AM;  AIX0305AZV=AIX0305AZM;  AIX0305AMV=AIX0305AMM;

    AIX0306SZV=AIX0306SZM;  AIX0306SDV=AIX0306SDM;  AIX0306_FV=AIX0306_FM;
    AIX0306_AV=AIX0306_AM;  AIX0306AZV=AIX0306AZM;  AIX0306AMV=AIX0306AMM;

    AIX0307SZV=AIX0307SZM;  AIX0307SDV=AIX0307SDM;  AIX0307_FV=AIX0307_FM;
    AIX0307_AV=AIX0307_AM;  AIX0307AZV=AIX0307AZM;  AIX0307AMV=AIX0307AMM;

    //--------------------

    AIFDFS_SZV=AIFDFS_SZM;  AIFDFS_SDV=AIFDFS_SDM;  AIFDFS__FV=AIFDFS__FM;
    AIFDFS__AV=AIFDFS__AM;  AIFDFS_AZV=AIFDFS_AZM;  AIFDFS_AMV=AIFDFS_AMM;

    AIFIMBMSZV=AIFIMBMSZM;  AIFIMBMSDV=AIFIMBMSDM;  AIFIMBM_FV=AIFIMBM_FM;
    AIFIMBM_AV=AIFIMBM_AM;  AIFIMBMAZV=AIFIMBMAZM;  AIFIMBMAMV=AIFIMBMAMM;

    AIFSHDFSZV=AIFSHDFSZM;  AIFSHDFSDV=AIFSHDFSDM;  AIFSHDF_FV=AIFSHDF_FM;
    AIFSHDF_AV=AIFSHDF_AM;  AIFSHDFAZV=AIFSHDFAZM;  AIFSHDFAMV=AIFSHDFAMM;

    AIFSVZ_SZV=AIFSVZ_SZM;  AIFSVZ_SDV=AIFSVZ_SDM;  AIFSVZ__FV=AIFSVZ__FM;
    AIFSVZ__AV=AIFSVZ__AM;  AIFSVZ_AZV=AIFSVZ_AZM;  AIFSVZ_AMV=AIFSVZ_AMM;

    AIFIM2SSZV=AIFIM2SSZM;  AIFIM2SSDV=AIFIM2SSDM;  AIFIM2S_FV=AIFIM2S_FM;
    AIFIM2S_AV=AIFIM2S_AM;  AIFIM2SAZV=AIFIM2SAZM;  AIFIM2SAMV=AIFIM2SAMM;

    AIFSD2SSZV=AIFSD2SSZM;  AIFSD2SSDV=AIFSD2SSDM;  AIFSD2S_FV=AIFSD2S_FM;
    AIFSD2S_AV=AIFSD2S_AM;  AIFSD2SAZV=AIFSD2SAZM;  AIFSD2SAMV=AIFSD2SAMM;

    AIFSP2SSZV=AIFSP2SSZM;  AIFSP2SSDV=AIFSP2SSDM;  AIFSP2S_FV=AIFSP2S_FM;
    AIFSP2S_AV=AIFSP2S_AM;  AIFSP2SAZV=AIFSP2SAZM;  AIFSP2SAMV=AIFSP2SAMM;

    AIX0407SZV=AIX0407SZM;  AIX0407SDV=AIX0407SDM;  AIX0407_FV=AIX0407_FM;
    AIX0407_AV=AIX0407_AM;  AIX0407AZV=AIX0407AZM;  AIX0407AMV=AIX0407AMM;

    //--------------------

    AILNS1SSZV=AILNS1SSZM;  AILNS1SSDV=AILNS1SSDM;  AILNS1S_FV=AILNS1S_FM;
    AILNS1S_AV=AILNS1S_AM;  AILNS1SAZV=AILNS1SAZM;  AILNS1SAMV=AILNS1SAMM;

    AILFS1SSZV=AILFS1SSZM;  AILFS1SSDV=AILFS1SSDM;  AILFS1S_FV=AILFS1S_FM;
    AILFS1S_AV=AILFS1S_AM;  AILFS1SAZV=AILFS1SAZM;  AILFS1SAMV=AILFS1SAMM;

    AILNS2SSZV=AILNS2SSZM;  AILNS2SSDV=AILNS2SSDM;  AILNS2S_FV=AILNS2S_FM;
    AILNS2S_AV=AILNS2S_AM;  AILNS2SAZV=AILNS2SAZM;  AILNS2SAMV=AILNS2SAMM;

    AILZSS_SZV=AILZSS_SZM;  AILZSS_SDV=AILZSS_SDM;  AILZSS__FV=AILZSS__FM;
    AILZSS__AV=AILZSS__AM;  AILZSS_AZV=AILZSS_AZM;  AILZSS_AMV=AILZSS_AMM;

    AILZO1SSZV=AILZO1SSZM;  AILZO1SSDV=AILZO1SSDM;  AILZO1S_FV=AILZO1S_FM;
    AILZO1S_AV=AILZO1S_AM;  AILZO1SAZV=AILZO1SAZM;  AILZO1SAMV=AILZO1SAMM;

    AILZO2SSZV=AILZO2SSZM;  AILZO2SSDV=AILZO2SSDM;  AILZO2S_FV=AILZO2S_FM;
    AILZO2S_AV=AILZO2S_AM;  AILZO2SAZV=AILZO2SAZM;  AILZO2SAMV=AILZO2SAMM;

    AILZSVFSZV=AILZSVFSZM;  AILZSVFSDV=AILZSVFSDM;  AILZSVF_FV=AILZSVF_FM;
    AILZSVF_AV=AILZSVF_AM;  AILZSVFAZV=AILZSVFAZM;  AILZSVFAMV=AILZSVFAMM;

    AILZPR_SZV=AILZPR_SZM;  AILZPR_SDV=AILZPR_SDM;  AILZPR__FV=AILZPR__FM;
    AILZPR__AV=AILZPR__AM;  AILZPR_AZV=AILZPR_AZM;  AILZPR_AMV=AILZPR_AMM;

    //--------------------

    AIHBM3_SZV=AIHBM3_SZM;  AIHBM3_SDV=AIHBM3_SDM;  AIHBM3__FV=AIHBM3__FM;
    AIHBM3__AV=AIHBM3__AM;  AIHBM3_AZV=AIHBM3_AZM;  AIHBM3_AMV=AIHBM3_AMM;

    AIHBM6_SZV=AIHBM6_SZM;  AIHBM6_SDV=AIHBM6_SDM;  AIHBM6__FV=AIHBM6__FM;
    AIHBM6__AV=AIHBM6__AM;  AIHBM6_AZV=AIHBM6_AZM;  AIHBM6_AMV=AIHBM6_AMM;

    AIX0602SZV=AIX0602SZM;  AIX0602SDV=AIX0602SDM;  AIX0602_FV=AIX0602_FM;
    AIX0602_AV=AIX0602_AM;  AIX0602AZV=AIX0602AZM;  AIX0602AMV=AIX0602AMM;

    AIHP1STSZV=AIHP1STSZM;  AIHP1STSDV=AIHP1STSDM;  AIHP1ST_FV=AIHP1ST_FM;
    AIHP1ST_AV=AIHP1ST_AM;  AIHP1STAZV=AIHP1STAZM;  AIHP1STAMV=AIHP1STAMM;

    AIH1ST_SZV=AIH1ST_SZM;  AIH1ST_SDV=AIH1ST_SDM;  AIH1ST__FV=AIH1ST__FM;
    AIH1ST__AV=AIH1ST__AM;  AIH1ST_AZV=AIH1ST_AZM;  AIH1ST_AMV=AIH1ST_AMM;

    AIH2ST_SZV=AIH2ST_SZM;  AIH2ST_SDV=AIH2ST_SDM;  AIH2ST__FV=AIH2ST__FM;
    AIH2ST__AV=AIH2ST__AM;  AIH2ST_AZV=AIH2ST_AZM;  AIH2ST_AMV=AIH2ST_AMM;

    AIX0606SZV=AIX0606SZM;  AIX0606SDV=AIX0606SDM;  AIX0606_FV=AIX0606_FM;
    AIX0606_AV=AIX0606_AM;  AIX0606AZV=AIX0606AZM;  AIX0606AMV=AIX0606AMM;

    AIX0607SZV=AIX0607SZM;  AIX0607SDV=AIX0607SDM;  AIX0607_FV=AIX0607_FM;
    AIX0607_AV=AIX0607_AM;  AIX0607AZV=AIX0607AZM;  AIX0607AMV=AIX0607AMM;

    //--------------------

    AOHBM6_LOV=AOHBM6_LOM;  AOHBM6_HOV=AOHBM6_HOM;
    AOHBM6_LPV=AOHBM6_LPM;  AOHBM6_HPV=AOHBM6_HPM;

    AOFDFS_LOV=AOFDFS_LOM;  AOFDFS_HOV=AOFDFS_HOM;
    AOFDFS_LPV=AOFDFS_LPM;  AOFDFS_HPV=AOFDFS_HPM;

    AOH1ST_LOV=AOH1ST_LOM;  AOH1ST_HOV=AOH1ST_HOM;
    AOH1ST_LPV=AOH1ST_LPM;  AOH1ST_HPV=AOH1ST_HPM;

    AOH2ST_LOV=AOH2ST_LOM;  AOH2ST_HOV=AOH2ST_HOM;
    AOH2ST_LPV=AOH2ST_LPM;  AOH2ST_HPV=AOH2ST_HPM;

    //--------------------

    AOTNS11LOV=AOTNS11LOM;  AOTNS11HOV=AOTNS11HOM;
    AOTNS11LPV=AOTNS11LPM;  AOTNS11HPV=AOTNS11HPM;

    AOTNS12LOV=AOTNS12LOM;  AOTNS12HOV=AOTNS12HOM;
    AOTNS12LPV=AOTNS12LPM;  AOTNS12HPV=AOTNS12HPM;

    AOTNS13LOV=AOTNS13LOM;  AOTNS13HOV=AOTNS13HOM;
    AOTNS13LPV=AOTNS13LPM;  AOTNS13HPV=AOTNS13HPM;

    AOTFS1SLOV=AOTFS1SLOM;  AOTFS1SHOV=AOTFS1SHOM;
    AOTFS1SLPV=AOTFS1SLPM;  AOTFS1SHPV=AOTFS1SHPM;

    //--------------------

    AOTDVP_LOV=AOTDVP_LOM;  AOTDVP_HOV=AOTDVP_HOM;
    AOTDVP_LPV=AOTDVP_LPM;  AOTDVP_HPV=AOTDVP_HPM;

    AOPGOK_LOV=AOPGOK_LOM;  AOPGOK_HOV=AOPGOK_HOM;
    AOPGOK_LPV=AOPGOK_LPM;  AOPGOK_HPV=AOPGOK_HPM;

    AOFDFS_LOV=AOFDFS_LOM;  AOFDFS_HOV=AOFDFS_HOM;
    AOFDFS_LPV=AOFDFS_LPM;  AOFDFS_HPV=AOFDFS_HPM;

    AOX0903LOV=AOX0903LOM;  AOX0903HOV=AOX0903HOM;
    AOX0903LPV=AOX0903LPM;  AOX0903HPV=AOX0903HPM;
    // резерв (для теста)
    AOX0903OOV=AOX0903_OM;  AOX0903_OV=AOX0903_OM;

    //--------------------

    AOFIMODLOV=AOFIMODLOM;  AOFIMODHOV=AOFIMODHOM;
    AOFIMODLPV=AOFIMODLPM;  AOFIMODHPV=AOFIMODHPM;

    AOFSVZ_LOV=AOFSVZ_LOM;  AOFSVZ_HOV=AOFSVZ_HOM;
    AOFSVZ_LPV=AOFSVZ_LPM;  AOFSVZ_HPV=AOFSVZ_HPM;

    AOFIM2SLOV=AOFIM2SLOM;  AOFIM2SHOV=AOFIM2SHOM;
    AOFIM2SLPV=AOFIM2SLPM;  AOFIM2SHPV=AOFIM2SHPM;

    AOFSPBMLOV=AOFSPBMLOM;  AOFSPBMHOV=AOFSPBMHOM;
    AOFSPBMLPV=AOFSPBMLPM;  AOFSPBMHPV=AOFSPBMHPM;

    //------------------------------------------------------------------------
    // Проверка ввода времени продувок

    if(TMPH_BM3_W<0 || TMPH_BM3_W>23 ){ TMPH_BM3_W=0; }
    if(TMPM_BM3_W<0 || TMPM_BM3_W>59 ){ TMPM_BM3_W=5; }
    if(TMPS_BM3_W<0 || TMPS_BM3_W>59 ){ TMPS_BM3_W=0; }
    if(TMWH_BM3_W<0 || TMWH_BM3_W>23 ){ TMWH_BM3_W=0; }
    if(TMWM_BM3_W<0 || TMWM_BM3_W>59 ){ TMWM_BM3_W=40;}
    if(TMWS_BM3_W<0 || TMWS_BM3_W>59 ){ TMWS_BM3_W=0; }
           
    if(TMPH_BM6_W<0 || TMPH_BM6_W>23 ){ TMPH_BM6_W=0; }
    if(TMPM_BM6_W<0 || TMPM_BM6_W>59 ){ TMPM_BM6_W=5; }
    if(TMPS_BM6_W<0 || TMPS_BM6_W>59 ){ TMPS_BM6_W=0; }
    if(TMWH_BM6_W<0 || TMWH_BM6_W>23 ){ TMWH_BM6_W=0; }
    if(TMWM_BM6_W<0 || TMWM_BM6_W>59 ){ TMWM_BM6_W=40;}
    if(TMWS_BM6_W<0 || TMWS_BM6_W>59 ){ TMWS_BM6_W=0; }
                                                   
    if(TMPH_HDF_W<0 || TMPH_HDF_W>23 ){ TMPH_HDF_W=0; }
    if(TMPM_HDF_W<0 || TMPM_HDF_W>59 ){ TMPM_HDF_W=5; }
    if(TMPS_HDF_W<0 || TMPS_HDF_W>59 ){ TMPS_HDF_W=0; }
    if(TMWH_HDF_W<0 || TMWH_HDF_W>23 ){ TMWH_HDF_W=0; }
    if(TMWM_HDF_W<0 || TMWM_HDF_W>59 ){ TMWM_HDF_W=40;}
    if(TMWS_HDF_W<0 || TMWS_HDF_W>59 ){ TMWS_HDF_W=0; }
                                                   
    if(TMPH_GDF_W<0 || TMPH_GDF_W>23 ){ TMPH_GDF_W=0; }
    if(TMPM_GDF_W<0 || TMPM_GDF_W>59 ){ TMPM_GDF_W=5; }
    if(TMPS_GDF_W<0 || TMPS_GDF_W>59 ){ TMPS_GDF_W=0; }
    if(TMWH_GDF_W<0 || TMWH_GDF_W>23 ){ TMWH_GDF_W=0; }
    if(TMWM_GDF_W<0 || TMWM_GDF_W>59 ){ TMWM_GDF_W=40;}
    if(TMWS_GDF_W<0 || TMWS_GDF_W>59 ){ TMWS_GDF_W=0; }
                                                   
    if(TMPH_P1S_W<0 || TMPH_P1S_W>23 ){ TMPH_P1S_W=0; }
    if(TMPM_P1S_W<0 || TMPM_P1S_W>59 ){ TMPM_P1S_W=5; }
    if(TMPS_P1S_W<0 || TMPS_P1S_W>59 ){ TMPS_P1S_W=0; }
    if(TMWH_P1S_W<0 || TMWH_P1S_W>23 ){ TMWH_P1S_W=0; }
    if(TMWM_P1S_W<0 || TMWM_P1S_W>59 ){ TMWM_P1S_W=40;}
    if(TMWS_P1S_W<0 || TMWS_P1S_W>59 ){ TMWS_P1S_W=0; }
                                                   
    if(TMPH_1ST_W<0 || TMPH_1ST_W>23 ){ TMPH_1ST_W=0; }
    if(TMPM_1ST_W<0 || TMPM_1ST_W>59 ){ TMPM_1ST_W=5; }
    if(TMPS_1ST_W<0 || TMPS_1ST_W>59 ){ TMPS_1ST_W=0; }
    if(TMWH_1ST_W<0 || TMWH_1ST_W>23 ){ TMWH_1ST_W=0; }
    if(TMWM_1ST_W<0 || TMWM_1ST_W>59 ){ TMWM_1ST_W=40;}
    if(TMWS_1ST_W<0 || TMWS_1ST_W>59 ){ TMWS_1ST_W=0; }
                                                   
    if(TMPH_D2S_W<0 || TMPH_D2S_W>23 ){ TMPH_D2S_W=0; }
    if(TMPM_D2S_W<0 || TMPM_D2S_W>59 ){ TMPM_D2S_W=5; }
    if(TMPS_D2S_W<0 || TMPS_D2S_W>59 ){ TMPS_D2S_W=0; }
    if(TMWH_D2S_W<0 || TMWH_D2S_W>23 ){ TMWH_D2S_W=0; }
    if(TMWM_D2S_W<0 || TMWM_D2S_W>59 ){ TMWM_D2S_W=40;}
    if(TMWS_D2S_W<0 || TMWS_D2S_W>59 ){ TMWS_D2S_W=0; }
                                                   
    if(TMPH_2ST_W<0 || TMPH_2ST_W>23 ){ TMPH_2ST_W=0; }
    if(TMPM_2ST_W<0 || TMPM_2ST_W>59 ){ TMPM_2ST_W=5; }
    if(TMPS_2ST_W<0 || TMPS_2ST_W>59 ){ TMPS_2ST_W=0; }
    if(TMWH_2ST_W<0 || TMWH_2ST_W>23 ){ TMWH_2ST_W=0; }
    if(TMWM_2ST_W<0 || TMWM_2ST_W>59 ){ TMWM_2ST_W=40;}
    if(TMWS_2ST_W<0 || TMWS_2ST_W>59 ){ TMWS_2ST_W=0; }
    
    return;
}
//----------------------------------------------------------------------------
