//---------------------------------------------------------------------------
#include "..\_libpath.inc"
#include "..\prg\run_prgv.h"
#include "..\prg\run_prgr.h"

#include "other_e.h"

//---------------------------------------------------------------------------
//  Присвоение значений переменным
vd  far SetVal(vd){

    //-----------------------------------------------------------------------
    // Обновление значений диапазонов и сигнализации
    AIF1P__SZV=AIF1P__SZM; AIF1P__SDV=AIF1P__SDM;
    AIF1P___FV=AIF1P___FM; AIF1P___AV=AIF1P___AM;
    AIF1P__AZV=AIF1P__AZM; AIF1P__AMV=AIF1P__AMM;

    AIF2P__SZV=AIF2P__SZM; AIF2P__SDV=AIF2P__SDM;
    AIF2P___FV=AIF2P___FM; AIF2P___AV=AIF2P___AM;
    AIF2P__AZV=AIF2P__AZM; AIF2P__AMV=AIF2P__AMM;

    AIL1C__SZV=AIL1C__SZM; AIL1C__SDV=AIL1C__SDM;
    AIL1C___FV=AIL1C___FM; AIL1C___AV=AIL1C___AM;
    AIL1C__AZV=AIL1C__AZM; AIL1C__AMV=AIL1C__AMM;

    AIL2C__SZV=AIL2C__SZM; AIL2C__SDV=AIL2C__SDM;
    AIL2C___FV=AIL2C___FM; AIL2C___AV=AIL2C___AM;
    AIL2C__AZV=AIL2C__AZM; AIL2C__AMV=AIL2C__AMM;

    AIP1P__SZV=AIP1P__SZM; AIP1P__SDV=AIP1P__SDM;
    AIP1P___FV=AIP1P___FM; AIP1P___AV=AIP1P___AM;
    AIP1P__AZV=AIP1P__AZM; AIP1P__AMV=AIP1P__AMM;

    AIP2P__SZV=AIP2P__SZM; AIP2P__SDV=AIP2P__SDM;
    AIP2P___FV=AIP2P___FM; AIP2P___AV=AIP2P___AM;
    AIP2P__AZV=AIP2P__AZM; AIP2P__AMV=AIP2P__AMM;

    AIP12V_SZV=AIP12V_SZM; AIP12V_SDV=AIP12V_SDM;
    AIP12V__FV=AIP12V__FM; AIP12V__AV=AIP12V__AM;
    AIP12V_AZV=AIP12V_AZM; AIP12V_AMV=AIP12V_AMM;

    AIP12M_SZV=AIP12M_SZM; AIP12M_SDV=AIP12M_SDM;
    AIP12M__FV=AIP12M__FM; AIP12M__AV=AIP12M__AM;
    AIP12M_AZV=AIP12M_AZM; AIP12M_AMV=AIP12M_AMM;

    AIT1TOPSZV=AIT1TOPSZM; AIT1TOPSDV=AIT1TOPSDM;
    AIT1TOP_FV=AIT1TOP_FM; AIT1TOP_AV=AIT1TOP_AM;
    AIT1TOPAZV=AIT1TOPAZM; AIT1TOPAMV=AIT1TOPAMM;

    AIT1BOTSZV=AIT1BOTSZM; AIT1BOTSDV=AIT1BOTSDM;
    AIT1BOT_FV=AIT1BOT_FM; AIT1BOT_AV=AIT1BOT_AM;
    AIT1BOTAZV=AIT1BOTAZM; AIT1BOTAMV=AIT1BOTAMM;

    AIT1P__SZV=AIT1P__SZM; AIT1P__SDV=AIT1P__SDM;
    AIT1P___FV=AIT1P___FM; AIT1P___AV=AIT1P___AM;
    AIT1P__AZV=AIT1P__AZM; AIT1P__AMV=AIT1P__AMM;

    AIS1PI_SZV=AIS1PI_SZM; AIS1PI_SDV=AIS1PI_SDM;
    AIS1PI__FV=AIS1PI__FM; AIS1PI__AV=AIS1PI__AM;
    AIS1PI_AZV=AIS1PI_AZM; AIS1PI_AMV=AIS1PI_AMM;

    AIS1PO_SZV=AIS1PO_SZM; AIS1PO_SDV=AIS1PO_SDM;
    AIS1PO__FV=AIS1PO__FM; AIS1PO__AV=AIS1PO__AM;
    AIS1PO_AZV=AIS1PO_AZM; AIS1PO_AMV=AIS1PO_AMM;

    AIS1CO_SZV=AIS1CO_SZM; AIS1CO_SDV=AIS1CO_SDM;
    AIS1CO__FV=AIS1CO__FM; AIS1CO__AV=AIS1CO__AM;
    AIS1CO_AZV=AIS1CO_AZM; AIS1CO_AMV=AIS1CO_AMM;

    AIS2PI_SZV=AIS2PI_SZM; AIS2PI_SDV=AIS2PI_SDM;
    AIS2PI__FV=AIS2PI__FM; AIS2PI__AV=AIS2PI__AM;
    AIS2PI_AZV=AIS2PI_AZM; AIS2PI_AMV=AIS2PI_AMM;

    AIS2PO_SZV=AIS2PO_SZM; AIS2PO_SDV=AIS2PO_SDM;
    AIS2PO__FV=AIS2PO__FM; AIS2PO__AV=AIS2PO__AM;
    AIS2PO_AZV=AIS2PO_AZM; AIS2PO_AMV=AIS2PO_AMM;

    AIS2CO_SZV=AIS2CO_SZM; AIS2CO_SDV=AIS2CO_SDM;
    AIS2CO__FV=AIS2CO__FM; AIS2CO__AV=AIS2CO__AM;
    AIS2CO_AZV=AIS2CO_AZM; AIS2CO_AMV=AIS2CO_AMM;

    N1AC06_SZV=N1AC06_SZM; N1AC06_SDV=N1AC06_SDM;
    N1AC06__FV=N1AC06__FM; N1AC06__AV=N1AC06__AM;
    N1AC06_AZV=N1AC06_AZM; N1AC06_AMV=N1AC06_AMM;

    N1AC07_SZV=N1AC07_SZM; N1AC07_SDV=N1AC07_SDM;
    N1AC07__FV=N1AC07__FM; N1AC07__AV=N1AC07__AM;
    N1AC07_AZV=N1AC07_AZM; N1AC07_AMV=N1AC07_AMM;

    AIT2TOPSZV=AIT2TOPSZM; AIT2TOPSDV=AIT2TOPSDM;
    AIT2TOP_FV=AIT2TOP_FM; AIT2TOP_AV=AIT2TOP_AM;
    AIT2TOPAZV=AIT2TOPAZM; AIT2TOPAMV=AIT2TOPAMM;

    AIT2BOTSZV=AIT2BOTSZM; AIT2BOTSDV=AIT2BOTSDM;
    AIT2BOT_FV=AIT2BOT_FM; AIT2BOT_AV=AIT2BOT_AM;
    AIT2BOTAZV=AIT2BOTAZM; AIT2BOTAMV=AIT2BOTAMM;

    AIT2P__SZV=AIT2P__SZM; AIT2P__SDV=AIT2P__SDM;
    AIT2P___FV=AIT2P___FM; AIT2P___AV=AIT2P___AM;
    AIT2P__AZV=AIT2P__AZM; AIT2P__AMV=AIT2P__AMM;

    return;
}
//---------------------------------------------------------------------------
